- CMakeLists.txt
Related: https://github.com/erikd/libsndfile/issues/71
Closes: https://github.com/erikd/libsndfile/issues/220
> CMake: Fix docs installation path

- doc/Makefile.am
Closes: https://github.com/erikd/libsndfile/issues/201
> doc/Makefile.am: Add missing print.css

- src/common.c
- src/float32.c
- src/sndfile.hh
- tests/checksum_test.c
- tests/command_test.c
- tests/floating_point_test.tpl
- tests/format_check_test.c
- tests/header_test.tpl
- tests/pipe_test.tpl
- tests/utils.tpl
Fix multiple errors uncovered by Clang's Memory Sanitizer.
Closes: https://github.com/erikd/libsndfile/issues/248
@evpobr Please test this patch.
> Fix MSAN errors

- src/common.c
Closes: https://github.com/erikd/libsndfile/issues/272
> src/common.c: Fix typo

- src/sfconfig.h
- src/sfendian.h
Regression introduced in commit 8321896.
Reported by Anonymous Maarten.
Closes: https://github.com/erikd/libsndfile/pull/306
> Fix x86/x86_64 CPU detection regression

- src/common.c
Spotted whilst working on the mp3 support stuff.
> Fix typo in macro name

- README.md
- appveyor.yml
- tests/win32_ordinal_test.c
Adds AppVeyor CI integration to test with Visual Studio.
Also adds required fix for `win32_ordinal_test` since it fails under Windows. 
Generated DEF file name is `libsndfile-1.def` with both Autotools and CMake:
https://github.com/erikd/libsndfile/blob/fa92cc4b8832f9651f178f81cd8d69c063c686b7/configure.ac#L597
https://github.com/erikd/libsndfile/blob/fa92cc4b8832f9651f178f81cd8d69c063c686b7/CMakeLists.txt#L399-L401
But `win32_ordinal_test` tries to check DLL against `libsndfile.def`:
https://github.com/erikd/libsndfile/blob/fa92cc4b8832f9651f178f81cd8d69c063c686b7/tests/win32_ordinal_test.c#L94
And it is the only failing test on `master` branch:
```
1>------ Build started: Project: RUN_TESTS, Configuration: Debug Win32 ------
1>Test project …
```
> Add AppVeyor CI script

- .gitignore
- Makefile.am
Closes: https://github.com/erikd/libsndfile/issues/369
Signed-off-by: Erik de Castro Lopo <erikd@mega-nerd.com>
> Makefile.am: Use more portable suffix rules

- src/aiff.c
- src/common.c
- src/common.h
- src/sndfile.c
- src/wav.c
- src/wavlike.c
- tests/command_test.c
- tests/cue_test.c
- tests/utils.tpl
This work was originally submitted by Diemo Schwarz <schwarz@ircam.fr> in
PR https://github.com/erikd/libsndfile/pull/197 which was rebased and
cleaned up.
Closes: https://github.com/erikd/libsndfile/pull/197
> Add support for more than 1000 cue points

- programs/sndfile-deinterleave.c
- src/chunk.c
- src/file_io.c
- src/mpc2k.c
Fixes #437 (and several other similar warnings treated as errors)
> Handle snprintf() format warnings

- src/file_io.c
Replace obsolete WinAPI functions `SetFilePointer` with `SetFilePointerEx`, `GetFileSize` with `GetFileSizeEx`.
New functions support 64-bit offsets directly, available at least on Win95, so nothing breaks.
Old functions are relics from Win 3.x 16-bit world.
> Use modern WinAPI functions

- azure-pipelines.yml
This PR integrates [Azure Pipelines](https://github.com/marketplace/azure-pipelines).
Testing Windows\Linux\macOS with Autotools\CMake takes about 10 min.
> [WIP] Integrate Azure Pipelines CI

- programs/common.c
- programs/sndfile-convert.c
- src/ogg.c
- src/ogg_opus.c
- src/ogg_vcomment.c
Fix a small number of errors found by fuzz testing. Also some minor stylistic fixes.
@arthurt  Would really appreciate your review of these changes. If you need me to, I can split these into fuzzing fixes and cosmetic change commits.
> Fixes to Opus handling

- src/w64.c
Closes: https://github.com/erikd/libsndfile/pull/509
> Wave64: Permit and skip arbitrary chunks prior to the data chunk

- src/sd2.c
- src/wavlike.c
Closes: https://github.com/erikd/libsndfile/issues/527
> src/wavlike.c: Fix compiler warning

- src/sfendian.h
Hundreds conversion warnings with MSVC compiler.
> Fix bunch of conversion warnings

- doc/api.html
> Explain sf_read_XXX behaviour

- CMakeLists.txt
> CMake: Install two forgotten man pages

- ossfuzz/ci_oss.sh
This _should_ build the OSS-Fuzz image in CI :smile:
> OSS-Fuzz - enable building in Github Actions CI

- src/file_io.c
Fix VS and VS Code IntelliSense.
> Refactor file.io includes

- include/sndfile.h.in
* Drop special condition for VC <= 2003
* Fix SF_COUNT_MAX redefine in config.h
> SF_COUNT_MAX define tweaks

- CMakeLists.txt
Avoid unknown policy error.
Related to #546.
> Fix CMake policy CMP0091 handling

- CMakeLists.txt
- NEWS
- configure.ac
- doc/api.html
- doc/command.html
- doc/formats.html
- doc/index.html
> Release 1.0.30

- CMakeLists.txt
- NEWS
`sndfile` name was dirty hack for Vcpkg.
> Change CMake project name to libsndfile

- src/wav.c
> Fix memory leak in wav_read_smpl_chunk()

- src/aiff.c
> Fix aiff_read_header() memory leak

- ossfuzz/ci_oss.sh
Update the name of the repository in the CI script
> Fix up git repository in ci_oss.sh

- src/wav.c
Credit to OSS-Fuzz (issue 25499)
---
@evpobr - from a code read this looks like a safe fix. Happy to fix up any problems though.
> Fix leak in wav_read_header

- src/wav.c
> Fix memory leak in wav_read_acid_chunk

- .github/workflows/action.yml
This is temporary fix.
https://github.com/actions/virtual-environments/issues/1811
> Fix GitHub Actions CI macOS build errors

- src/aiff.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26613
> Fix memory leak in aiff_read_basc_chunk

- src/wavlike.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26703
> Fix memory leak in wavlike_read_peak_chunk

- src/aiff.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26812
> Fix memory leak in aiff_read_header

- src/wav.c
> Improve handling of SMPL chunks in WAV files.

- docs/api.md
> fix api.md table error

- include/sndfile.h.in
Working on #674 and similar cases of reserved header data if there is any.
> Improving header documentation.

- CONTRIBUTING.md
1. Separate subject from body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line
3. Do not end the subject line with a period
4. Use the imperative mood in the subject line
5. Wrap the body at 72 characters
6. Use the body to explain what and why vs. how
> Add commit message requirements to CONTRIBUTING.md

- src/ogg_vorbis.c
Previously the `vorbis_seek()` function did not take the lapped nature of Vorbis block into account when using the bisection search.
Also, introduces `vorbis_skip()`, which can skip through packets without having to decode all the way to samples.
Fixes #643
> Fix for Issue 643: Vorbis Seek Offset.

- CONTRIBUTING.md
> Update commit message contributing guidlines

- Building-for-Android.md
Working sndfile integration on Android, used for a simple music player
> Add cmake build instructions for Android

- configure.ac
Related to [758](https://github.com/libsndfile/libsndfile/issues/758)
> configure.ac: Handle 'beta' suffix in WIN_RC_VERSION generation

- src/mpeg_decode.c
Rewrite the mpeg_dec_read_X() conversion copy loops for clarity and bug
fixes.
- Use two buffers rather than in-place expansion for float -> double
conversion of mpeg_dec_read_double(). The previous method required a
less-compiler optimizer friendly backwards looping. This also broke
strict-aliasing rules as well, (although this could be worked around
with a union pointer.)
- Add optional clipping support for float->short and float->int reads.
- Don't bother deref'ing and passing the otherwise unused
MPEG_DEC_PRIVATE pointer, instead deref it as needed in
mpeg_dec_decode().
> mpeg: Rewrite decode read conversion copy loops

- docs/development.md
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
> docs: Fix link to the main repository

- CHANGELOG.md
- src/common.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28441
> Fix integer overflow in psf_log_printf()

- CHANGELOG.md
- src/common.c
> Fix unintialized variable in psf_binheader_readf()

- CHANGELOG.md
- src/gsm610.c
related to https://github.com/libsndfile/libsndfile/issues/785
> Fix signed integer overflow

- CHANGELOG.md
- CMakeLists.txt
- configure.ac
doing the tarball diffs on Linux and macOS in the mean time
> Release 1.2.0

- programs/sndfile-metadata-set.c
Signed-off-by: Rosen Penev <rosenp@gmail.com>
> sndfile-metadata-set: add localtime_s support

- .github/workflows/cifuzz.yml
- Scripts/cstyle.py
- src/ogg.c
- src/ogg_opus.c
- src/ogg_vorbis.c
Fixes #1035
Improved error checking for Vorbis.
Also fixed the `cstyle.py` script.
> Issue 1035 Vorbis fixes

- configure.ac
- programs/sndfile-play.c
- src/sfconfig.h
Fixes #1031
@sohamsinh31 @fabiangreffrath please test
> Correctly request Sndio support

- CMakeLists.txt
> cmake version min 3.12

- CMakeLists.txt
ref: https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html
fixes #1072
> fix cmake min...max syntax
