libsndfile/libsndfile

CMakeLists.txt

* Use single `sndfile-play` target under all platforms
* Fix programs installation https://github.com/erikd/libsndfile/issues/219 
* Add `BUILD_PROGRAMS` option to control build programs or not

Cmake: Programs configuring fixes

---

src/test_main.c
tests/win32_ordinal_test.c

* src/test_main.c: Fix typo in HAVE_SYS_TYPES_H definition
* tests/win32_ordinal_test.c: Use correct "direct.h" header instead of "dirent.h"
Related: https://github.com/erikd/libsndfile/issues/154, https://github.com/erikd/libsndfile/pull/234

tests: Fix typos in fixes for MSVC

---

tests/win32_ordinal_test.c

The name of Win32 definition file was changed from `libsndfile-1.def` to `libsndfile.def`, test source is modified to reflect these changes.

Fix win32_ordinal_test

---

regtest/database.c

`getcwd` function requires `direct.h` header.

Fix sndfile-regtest compilation with MSVC

---

src/sd2.c

Unfortunately this bug cannot be found by the compiler and the tests
didn;t find it either. It was found during work to improve the type
safety of calls to psf_binheader_writef.

src/sd2.c: Fix a psf_binheader_writef usage bug

---

programs/sndfile-play.c

Seems ALSA wants float samples in the [-1.0, 1.0] range.
Closes: https://github.com/erikd/libsndfile/issues/275

sndfile-play.c: Fix scaling of float samples with ALSA.

---

programs/sndfile-salvage.c

programs/sndfile-salvage.c: Fix wrong filename in error message

---

src/common.c

Fixes the following problems:
1. Case 's' only enlarges the buffer by 16 bytes instead of size bytes.
2. psf_binheader_writef() enlarges the header buffer (if needed) prior to the
big switch statement by an amount (16 bytes) which is enough for all cases
where only a single value gets added. Cases 's', 'S', 'p' however
additionally write an arbitrary length block of data and again enlarge the
buffer to the required amount. However, the required space calculation does
not take into account the size of the length field which gets output before
the data.
3. Buffer size requirement calculation in case 'S' does not account for the
padding byte ("size += (size & 1) ;" happens after the calculation which
uses "size").
4. Case 'S' can overrun the header buffer by 1 byte when no padding is …

src/common.c: Fix heap buffer overflows when writing strings in binheader

---

examples/generate.c
examples/sndfile-loopify.c

These headers aren't used by the examples (as far as I could tell). Removing these includes would help make them look more like real user programs that may not have access to these files and make it faster and require less extra files to compile after copy-pasting somewhere else.

Remove unused internal header includes from examples.

---

src/sfendian.h

src/sfendian.h: Detect and use MSVC byte swap intrinsics

---

src/sfconfig.h

`__x86_64__`, `__i486__`, `__i586__`, `__i686__` are not defined under MSVC, so `CPU_IS_X86` and `CPU_IS_X86_64` are always `0`:
[MSDN: Predefined Macros](https://msdn.microsoft.com/en-US/library/b0084kay(v=vs.140).aspx)

src/sfconfig.h: Fix CPU architecture detection under Windows

---

src/sndfile.c

There were two handers for SFC_GET_LOG_INFO and one incorrectly was
not returning the length of log string.
Closes: https://github.com/erikd/libsndfile/issues/345

sndfile.c: Return the length of log output

---

programs/sndfile-play.c

We don't play on MacOSX >= 10.8 (the code for the new API is not written),
and support for MacOSX older than that was removed some time ago.
So drop the last remnants; we just don't play on MacOSX.

drop MacOSX from sndfile-play

---

programs/sndfile-convert.c

This fixes the problem noted in #43 where attempting to convert a stereo
WAV to SDS gives a misleading error about the codec, when the real problem
is that the output format only supports mono not stereo.
Signed-off-by: Erik de Castro Lopo <erikd@mega-nerd.com>

sndfile-convert: Check if conversion failed due to no. of channels

---

src/sndfile.c

If `data == NULL` string is not copied but command returns `SFE_BAD_COMMAND_PARAM (31)`. It can be misunsderstood as string length.
Related to issue #345.

src/sndfile.c: Set SFC_GET_LIB_VERSION return result to 0 on error

---

src/aiff.c
src/rf64.c
src/w64.c
src/wav.c

The code was allowing files to be written with a channel count of exactly
`SF_MAX_CHANNELS` but was failing to read some file formats with the same
channel count.

Fix max channel count bug

---

src/wavlike.c

Closes: https://github.com/erikd/libsndfile/issues/370

src/wav.c: Fix skipping of erroneous subchunks

---

src/ogg.c
src/ogg.h
src/ogg_vorbis.c

This pull request merges duplicate code from from src/ogg.c and src/ogg_vorbis.c into a common function.. The code in question is for reading the first page of an Ogg bitstream. The benefits of such a merge are:
1) Each codec encapsulated by Ogg requires the functionality, so future codecs may use it without duplication as well.
2) Removal of the duplicate code from src/ogg_vorbis.c allows for a more structured way for calling ogg_read_first_page () only as needed, remove the need for re-reading the beginning of the file. In my tests this fixes issue #110 .
This pull request also changes the way ogg_vorbis_open () and ogg_open () interact. Previously ogg_vorbis_open () assumed nothing about the state of the container state, re-initializing all Ogg related structures itself and assuming …

Avoid seeks in ogg_open (), Introduce ogg_read_first_page ()

---

src/wav.c
tests/command_test.c

This commit fixes libsndfile's Sampler Chunk parsing.
That way the fine tuning of the instrument get's parsed correctly.
There is a certain rounding error involved which might require further
investigation but it's better than not working at all.
Writing to WAV already works but reading didn't work until now.

src/wav.c: Fix WAV Sampler Chunk tune parsing

---

CMakeLists.txt

using the existing method of the list CMAKE_MODULE_PATH passed to include was causing multiple paths to be appended to one huge invalid path.
see docs here: CMake does this for you, with one caveat as long as there isn't a built in module with the same name, 
https://cmake.org/cmake/help/latest/command/include.html

modernize cmake module include.

---

src/alaw.c
src/ulaw.c

i2ulaw_array() and i2alaw_array() fail to handle ptr [count] = INT_MIN properly, leading to buffer underflow. INT_MIN is a special value since - INT_MIN cannot be represented as int.
In this case round - INT_MIN to INT_MAX and proceed as usual.
f2ulaw_array() and f2alaw_array() fail to handle ptr [count] = NaN properly, leading to null pointer dereference.
In this case, arbitrarily set the buffer value to 0.
Not sure 0 is the right value here.
This PR fixes #429 (CVE-2018-19661 + CVE-2018-19662), #344 (CVE-2017-17456 + CVE-2017-17457) and #317 (CVE-2017-14245 and CVE-2017-14246).

a/ulaw: fix multiple buffer overflows

---

src/wavlike.h

According to MSDN all the GUID fields are unsigned.
Fixes -Woverflow warnings in pedantic mode.

Fix EXT_SUBFORMAT struct

---

cmake/SndFileChecks.cmake
src/config.h.cmake

Fixes warning: `"__USE_MINGW_ANSI_STDIO" redefined`.
`__USE_MINGW_ANSI_STDIO` is required to use 64-bit numbers in
printf-like functions.

CMake: Fix warnings on MinGW platform

---

src/common.c
src/gsm610.c

Neither of these issues was of any concern, but they have been fixed to
avoid the static analysis warnings.
Closes: https://github.com/erikd/libsndfile/issues/445

Avoid two static analysis warnings

---

src/ogg_vorbis.c

Use new Ogg functionality merged with Opus support to reduce code duplication, simplify Vorbis support (decoding in particular) and improve seek performance.
This uses the bisection-based seek support, rather than decode-from-start seeking. This removes the need for a separate file decode for calculating file sample count. The 'nasty nest' is simplified and flattened out a bit.
No new tests are introduced, as no new functionality is exposed (other than less computationally expensive seeking.)
Had this on the back-burner ready to go once the Ogg changes required by the Opus pull request were merged.

Vorbis: Use new ogg functions, bisection seek support.

---

src/wav.c

If loop_count is bigger than the array, truncate it to the array
length (and not to 32k).
CVE-2019-3832

wav_write_header: don't read past the array end

---

CMakeLists.txt

Incorrect define check and non-existent argument used for install.

CMake: Fix installation of man pages.

---

configure.ac

* These are spurious and pollute logs unnecessarily.

Ignore `-Wformat-truncation` warnings

---

src/sndfile.hh

This PR simply replace 0 or NULL by nullptr. It allow compiling the code with the following compiler flags:
```
-Werror -Wzero-as-null-pointer-constant
```

Fix zero-as-null-pointer-constant-warning

---

CMakeLists.txt

Fixes #489 
Before this commit, command 1 succeeds but command 2 fails. After, both succeed.
```
cmake .. && make -j$(nproc)` # 1
cmake .. -DBUILD_SHARED_LIBS=ON && make -j$(nproc)` # 2
```
Please note that I don't know my way around CMake so feel free to edit this as needed.

Fix building programs while BUILD_SHARED_LIBS=ON

---

README
README.md

libopus is a build requirement for the external libs build, but it was not mentioned yet in the READMEs.

Add libopus to the build-dependency requirements in READMEs.

---

cmake/SndFileConfig.cmake.in

When libsndfile is configured with `ENABLE_EXTERNAL_LIBS=OFF`, the CMake Package Configuration file shouldn't look for the external libraries. Otherwise, the `return()` call in the `find_dependency()` macro causes `find_package(SndFile)` to fail if the libraries are not found.

Fix Package Configuration file when ENABLE_EXTERNAL_LIBS is OFF

---

programs/common.c
programs/common.h
programs/sndfile-convert.c

and check elements of the data[] array for being finite.
Both checks use functions provided by the <math.h> header as declared
by the C99 standard.
Fixes #317
CVE-2017-14245
CVE-2017-14246

sfe_copy_data_fp: check value of "max" variable for being normal

---

azure-pipelines.yml

Some test images were deprecated causing test build errors.
Visual Studio 2015 was removed and replaced with Visual Studio 2019.
macOS 10.13 was deprecated, replaced with macOS 10.15.

Update Azure Pipelines CI images

---

README.md

`opus` is the name of the Homebrew package, not `libopus`.

README.md: Fix the brew install command

---

src/ms_adpcm.c
src/ogg.c
tests/misc_test.c

Fix GCC 10.2.0 with `-Wall -Wextra` warnings.
1. src/ogg.c: Fix compiler warning
-Wsign-compare in ogg_stream_seek_page_search().
2. src/misc_test.c: Fix compiler warnings
-Wunused-parameter, -Wunused-variable in filesystem_full_test().
Windows platforms only.
3. src/ms_adpcm.c: Fix compiler warnings
-Wmaybe-uninitialized in msadpcm_encode_block().
4. src/ogg.c: Fix compiler warning
Comparison of distinct pointer types lacks a cast in ogg_read_first_page().

Fix compiler warnings

---

.github/workflows/action.yml
Makefile.am
configure.ac
ossfuzz/.gitignore
ossfuzz/ci_oss.sh
ossfuzz/ossfuzz.sh
ossfuzz/sndfile_fuzzer.cc
ossfuzz/standaloneengine.cc
ossfuzz/testinput.h

Fixes #476
Add a fuzzer (`sndfile_fuzzer`) which can be compiled and run by the OSS-Fuzz infrastructure.
---
This feature adds in a fuzzing program which is able to be compiled and run by OSS-Fuzz's overnight fuzzing infrastructure. It uses virtual IO for speed (which is different to the proposal by @Google-Autofuzz, but I think not writing files to disk is likely faster :smile)
Please let me know if you have any comments! If this is accepted then I'll push a PR to OSSFuzz to enable this in their overnights.

Add ossfuzz support for libsndfile

---

ossfuzz/ci_oss.sh
ossfuzz/ossfuzz.sh

Fixes #576
Don't use --enable-werror for OSS Fuzz CI at the moment so that OSS-Fuzz can compile things

Don't use --enable-werror in OSS-Fuzz job

---

CMakeLists.txt

Two manpages are installed by Autotools as symlinks, on some platforms
they are not visible and installation fails with error.
Install these files with renaming to avoid errors.
Related to edc513a, #m-ab-s/media-autobuild_suite#1801

CMake: Fix manpages installation on some platforms

---

src/file_io.c

`CreateFile` is not available on  [UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide) platform, use `CreateFile2` instead.
Patch from Vcpkg's libsndfile port.

Improve UWP support

---

src/sfendian.h

* Fix asm-optimized branch neved used (redefined by ENDSWAP_X
macros below).
* Reorganize standalone ifdefs to conditional flow.
* Add __has_builtin brach for modern compilers to use builtin GCC-compatible
intrinsics.

Improve endswap macros set

---

src/file_io.c

No `WINAPI_PARTITION_SYSTEM` define on MinGW platform.
Related to #584.

Fix compiler warning on MinGW platform

---

src/wavlike.c

Fix memory leak in wavlike_read_bext_chunk()

---

src/ogg_opus.c

Fix errors in parsing an OggOpus header packet where aliased pointers of different type widths are used with psf_binheader_readf(), resulting in incorrect data or endian issues. Telling psf_binheader_readf() to read an integer of fixed width, but then passing a pointer to an integer of a different width is a bug.

Opus: Fix integer bug in header parsing. Fixes issue #581.

---

include/sndfile.h.in

* A `_MSCVER` has never been a built-in for the MSVC compiler.
* Simply use the same `SF_COUNT_MAX` for all MSVC compilers.

[Win32] Fix for MSVC

---

regtest/database.c

To get a working `sndfile-regtest.exe` for Windows, the assumption of 
only `'/'` on paths caused strange and non-intuitive errors like: `Not a valid SNDFILE* pointer.`
And BTW, since the Windows-Kit has `winsqlite3.h`, this could be used instead of `sqlite3.h`. Later.

[Win32] support both '\\' and '/' in path-names

---

CMakeLists.txt

When building the library on MacOS 10.15, the application using it crash on the first readf() call:
```
System Integrity Protection: enabled
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Termination Reason:    DYLD, [0x4] Symbol missing
Dyld Error Message:
Symbol not found: ____chkstk_darwin
Referenced from: /Path/To/MyApplication.app/Contents/MacOS/../Frameworks/libsndfile.1.dylib (which was built for Mac OS X 10.15)
Expected in: /usr/lib/libSystem.B.dylib
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                          	0x0000000109df524a __abort_with_payload + 10
1   dyld …
```

Fix MacOS 10.13 compatibility

---

src/wavlike.c

Credit to OSS-Fuzz (issue 26368)
---
@evpobr this is a similar fix to https://github.com/libsndfile/libsndfile/commit/e9e31f60304c80a608711b3d59280a7252a47a08, so I fixed it in a similar way.

Fix leak in wavlike_read_cart_chunk

---

src/aiff.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25438

Fix memory leak in aiff_open

---

ossfuzz/sndfile_fuzzer.cc

Instead, print out the bad seek, e.g.
```
Running: /out/clusterfuzz-testcase-minimized-sndfile_fuzzer-4838501290606592
vf overseek: new_offset(539033364) > vf->length(20);  whence(1), vf->offset(20), offset(539033344)
vf overseek: new_offset(539033364) > vf->length(20);  whence(1), vf->offset(20), offset(539033344)
```

Fix up the fuzzer so that it can't under or overseek.

---

CMakeLists.txt

Sorry but I had a bad understanding on how to handle CMAKE_OSX_DEPLOYMENT_TARGET at the time of my last PR.

Remove CMAKE_OSX_DEPLOYMENT_TARGET which should be set by the consumer

---

docs/command.md

I believe this fixes an error in the documentation I found Here:
http://www.mega-nerd.com/libsndfile/command.html#SFC_GET_LOOP_INFO

SF_BROADCAST_INFO -> SF_LOOP_INFO

---

.gitattributes

having a .gitignore file in the git-archives (e.g. like the automated
archives provided by github) is rather annoying if the archive gets
imported in other repositories.
my use-case is the Debian packaging, where we really want to see any files created/modified during the build process.

Exclude repository-configuration from git-archive

---

cmake/sqlite/FindSQLite3.cmake

Adding libsndfile in NDK based android app is failing for this typo.

Fixed typo in FindSQLite3.cmake file

---

src/wavlike.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26712

Fix use of uninitialized value in exif_subchunk_parse

---

configure.ac

This fixes incompatibilities with the clang and gcc builds, and also
matches what is done in the CMake builds.

configure: Use version-script when compiling with clang on unix

---

src/sndfile.c

There is a small typo in src/sndfile.c.
Should read `supplied` rather than `suppiled`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, suppiled -> supplied

---

docs/command.md

Just some missing dots and a misspelling of "count".

Fixed typos in command documentation.

---

src/common.c
src/id3.c
src/sndfile.c

Fix a bug in id3.c where large ID3v2 headers would fail to seek to the embedded file. ID3v2 tags are skipped over, treating the wrapped file as an embedded file. `id3_skip()` sets the embedded file offset to be just after the ID3v2 tag ends, then seeks the `psf_binheader()` to the fileoffset.
`psf_binheader_read()` accomplishes seeks by either reading and buffering bytes until the offset is reached, or if the buffer would be too large, seeking the underlying file instead using `psf_fseek()`. `psf_fread()` does not take the embedded file offset into account, while `psf_fseek()` does.
In the case of ID3 tags larger than the binheader buffer max, this has the effect of seeking to twice the id3v2 tag length, as
`psf_fseek(fileoffset, SEEK_CUR)` adds the fileoffset to the offset argument …

ID3v2 skip fixes

---

src/command.c

I wrote this bit of code for getting all the available extensions supported by libsndfile:
```cpp
QList<QString> extensions;
int count;
sf_command(nullptr, SFC_GET_FORMAT_MAJOR_COUNT, &count, sizeof(int));
for (int i = 0; i < count; i++) {
SF_FORMAT_INFO info;
info.format = i;
sf_command(nullptr, SFC_GET_FORMAT_MAJOR, &info, sizeof(info));
extensions.push_back(QString(info.extension).toLower());
};
return extensions;
```
Eventually I find out that my `ogg` files are ignored because the extension isn't included in `major_formats`
Perhaps we can also add `ogv` if that's supported. All extensions `oga`, `ogg` and `ogv` hold vorbis audio data.

Add .ogg to major_formats

---

src/double64.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25366

Fix use of uninitialized value in endswap_int64_t_array

---

CHANGELOG.md
src/caf.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30375

Fix memory leak in caf_read_header()

---

src/file_io.c

It is `INVALID_HANDLE_VALUE`, no idea why we should pretend that it is `NULL`.

Use proper error value for Win32 file handle

---

CHANGELOG.md
src/float32.c
tests/floating_point_test.tpl

This was initially spotted by inspection (I don't have hardware that falls back to using this path) but it was confirmed to be a bug after forcing `psf->ieee_replace` to be enabled in `psf_open_file()` and re-running the test suite.
Along with a patch to fix the normalisation, I've also extended `floating_point_test.tpl` to add tests that would have caught the incorrect normalisation.

Fix int normalisation when reading in floats with the replacement reader

---

regtest/database.c
src/ALAC/alac_codec.h
src/ALAC/alac_decoder.c
src/alac.c
src/common.c
src/common.h
src/test_broadcast_var.c
src/wav.c
tests/error_test.c

Warnings were spotted when compiling with `-Wall -Wextra -pedantic` using clang and GCC. This PR fixes all of the clang warnings, and most of the GCC warnings. The remaining GCC warnings are all `-Wformat-truncation=` where the buffer being written to is intentionally missing the terminating `NUL` (for example, `SF_BROADCAST_INFO::origination_date` which holds `"YYYY/MM/DD"` in 10 `char`s), but I've left them since I'm using clang.

Fix pedantic warnings

---

include/sndfile.h.in

For developers it is typedef to the actual `sf_private_tag` struct now.
For users it is still opaque type (no API break).

Change SNDFILE type to be a typedef of a real struct

---

src/avr.c
src/caf.c
src/common.h
src/ima_adpcm.c
src/mpc2k.c
src/sndfile.c
src/svx.c

This is the first batch of fixes for issues found by fuzzing `libsndfile` locally. UBSan has picked up another 140 issues (number still rising as fuzzing continues) but those are presumably of lower priority than the security issues I've since spotted on https://bugs.chromium.org/p/oss-fuzz/issues/list?q=libsndfile (which were all reported last year). The next batch of fixes will be in a separate PR once I find time to look into them.

Fuzzer fixes

---

CMakeLists.txt

This PR simply adds the `generate` example executable to the CMake build. This makes generating an initial corpus for fuzzing slightly easier.

Add the generate example to the CMake build

---

CHANGELOG.md
include/sndfile.h.in
include/sndfile.hh
src/windows.c
tests/locale_test.c

Use standard `_WIN32` define instead. Any sane compiler on Windows platfrom defines `_WIN32`.
The `wpath` parameter type has been changed to an equivalent type that does not require the inclusion of the `windows.h` header.

Deprecate ENABLE_SNDFILE_WINDOWS_PROTOTYPES define

---

src/ms_adpcm.c
src/wavlike.c

This PR fixes the security issues spotted by oss-fuzz in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26026 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26803. Of the other publicly visible security issues only https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27503 looks frightening, and that looks like it'll go away once the UBSan issues in ALAC are fixed.

oss-fuzz ASAN fixes

---

tests/alaw_test.c
tests/command_test.c
tests/compression_size_test.c
tests/floating_point_test.tpl
tests/header_test.tpl
tests/headerless_test.c
tests/lossy_comp_test.c
tests/string_test.c
tests/ulaw_test.c
tests/utils.tpl
tests/write_read_test.tpl

`ctest -j <N>` can fail sporadically due to tests sharing the same temporary file names. This PR fixes the issue by changing the names of all those that conflict.
I'm not sure if `get_unique_test_name()` is the best approach, but it was simpler than changing every string.

Change test file names to avoid conflicts when running tests

---

src/sfendian.h

MSVC has `__has_builtin`, but no `__builtin_bswapXX` intrinsics, so the unoptimized version is always used.

Fix byteswap optimizations detection

---

include/sndfile.hh

This reverts commit 2269af84173c1f70b6d700fa167e1e8ea01d7247.
The code which defined nullptr mysteriously broke the Windows build for
SuperCollider. After some investigation I discovered this commit to be the
cause, as MSVC by default does not set __cplusplus to anything greater
than 199711L unless explicitly asked to.
In general, #defining a keyword like nullptr in a library header is not
courteous, as it can affect compilation of later code and cause
significant confusion. This was exactly the situation I encountered, and
it took several days to track down the source.
The stated reason for the commit reverted by this was to prevent a
specific warning from appearing during compilation. However, there are
a few less intrusive ways of accomplishing this. For example, by using
`#pragma`s …

Revert "Fix zero-as-null-pointer-constant-warning"

---

.github/workflows/action.yml
CMakeLists.txt
Makefile.am
cmake/FindLame.cmake
cmake/FindMpg123.cmake
cmake/SndFileChecks.cmake
configure.ac
include/sndfile.h.in
programs/common.c
src/command.c
src/common.c
src/common.h
src/config.h.cmake
src/id3.c
src/id3.h
src/mp3.c
src/mpeg.c
src/mpeg.h
src/mpeg_decode.c
src/mpeg_l3_encode.c
src/sndfile.c
src/test_log_printf.c
tests/command_test.c
tests/compression_size_test.c
tests/floating_point_test.tpl
tests/format_check_test.c
tests/mp3_test.c
tests/mpeg_test.c
tests/string_test.c
tests/test_wrapper.sh.in

MPEG Encode/Decode Support
Uses libmpg123 for decode, liblame for encode. Encoding and decoding support is independent of each other and is split into separate files. MPEG support is generalized as subformats, SF_FORMAT_MPEG_LAYER(I,II,III) so that it might be used by other containers (MPEG1WAVEFORMAT for example), but also contains a major format SF_FORMAT_MP3 for 'mp3 files.' 
Introduces the command SFC_GET_BITRATE_MODE/SFC_SET_BITRATE_MODE.
Encoding Status
- Layer III encoding
- ID3v1 writing
- ID3v2 writing
- Lame/Xing Tag writing
- Bitrate selection command
- VBR or CBR
Decoding Status
- Layers I/II/III decoding
- ID3v1 reading
- ID3v2 reading
- Seeking
Decoding Todo
- ~~mpg123 global init race~~
- ~~specific error codes~~
- ~~better decoder corruption handling~~
Future Possible …

MPEG Encode/Decode Support

---

programs/common.c
programs/sndfile-convert.c
programs/sndfile-info.c
src/ogg_opus.c

A few small fixes for the programs.
- (common) Add missing MPEG format handling in to string conversions.
- (common) Fix a style error that was somehow committed already!?
- (convert) Do floating point sample copying when either the source or destination is MPEG
- (convert) Infer Vorbis subformat from `.ogg` suffix. This aligns with what Xiph.org now recommends. `.oga` still means "Ogg container with audio" and is subformat agnostic.
- (common) Don't warn about Broadcast Chunk for MPEG WAV files. By the comment above, they are allowed by the RFC.
- (info) Calculate dB properly for Vorbis and Opus.
One non-program fix that's been bugging me for a while:
- For Opus, remove tabs injected into a pre-formated info-dump block of printfs, messing up the alignment.

Programs: Add MPEG functionality, Vorbis, Opus fixes

---

src/flac.c

flac: Fix improper buffer reusing

---

src/ALAC/alac_decoder.c

This PR fixes the crash seen in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27503 by re-enabling code that shouldn't have been disabled in the original import. AFAICT this is the original code: https://github.com/macosforge/alac/blob/master/codec/ALACDecoder.cpp#L588-L593. However since we're importing this we would want it to be in release mode with this check enabled by default. Without this check `channelIndex` can increase without bounds and that leads to writing past the end of the output buffer.

Fix heap-buffer-overflow in copyPredictorTo24

---

CHANGELOG.md
CMakeLists.txt

Now ABI version must be compatible with Autotools builds. Note that this change requires CMake >= 3.17 for building dylib on Apple platforms.

Fix CMake shared library ABI version on Apple platforms

---

CMakeLists.txt
Makefile.am
cmake/SetupABIVersions.cmake

This change will make release process easier - bump `lt_current`, `lt_revision` and `lt_age` in `configure.ac` and CMake will update ABI version on configure or build.

Read CMake ABI version from configure.ac

---

CHANGELOG.md
Makefile.am
ossfuzz/ossfuzz.sh
ossfuzz/sndfile_alt_fuzzer.cc
ossfuzz/sndfile_fuzz_header.h
ossfuzz/sndfile_fuzzer.cc

Hi,
I have been working on extending the fuzzing of libsdnfile and would be very happy to start contributing more. This PR adds an initial fuzzer targeting `sf_read_double`, `sf_read_int` and `sf_read_short`. I think there are a few more things we could do to improve the fuzzing of libsndfile - let me know if you would appreciate more contributions in this area. 
David

Add new fuzzer for oss-fuzz

---

configure.ac

Add libopus to make missing external libraries warning correct.

Fix missing external libs message for Autotools

---

programs/sndfile-play.c

It was built with an error in FreeBSD:
```
programs/sndfile-play.c: In function 'alsa_write_float':
programs/sndfile-play.c:331:4: error: duplicate case value programs/sndfile-play.c:293:4: note: previously used here
```
because this file has defined `ESTRPIPE` as `EPIPE` in: `/usr/local/include/alsa/pcm.h:#define ESTRPIPE EPIPE`

Fix duplicated case value of ESTRPIPE on BSD

---

.github/workflows/action.yml

Speed up GitHub Actions CI using [Vcpkg binary caching feature](https://vcpkg.readthedocs.io/en/stable/users/binarycaching/).
Dependencies are built once and on next run restored from GitHub packages.

Add Vcpkg binary caching

---

configure.ac

* Clang produces warnings such as
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]

Only add `-Wno-format-truncation` when using GCC

---

src/g72x.c

Fixing signed integer overflow as reported in https://github.com/libsndfile/libsndfile/issues/757 . A similar fix was applied before https://github.com/libsndfile/libsndfile/pull/818

Fix signed integer overflow in g72x.c

---

src/flac.c

As discussed in issue #431: when reading a FLAC file, the `sf_read_*` or `sf_readf_*` functions will fail if the total number of samples exceeds 0x1000000, and the number of channels is not a power of two.
This is because (e.g.) `flac_read_flac2s` will invoke `flac_read_loop` with a buffer size of at most 0x1000000, and `flac_read_loop` requires the size to be a multiple of the number of channels.
This logic was introduced with commit d81614ca9068959884a6db3b78b8892e76055956, which unfortunately does not have a very detailed commit message.  That commit does two things that appear unrelated:
(1) It ensures that `flac_buffer_copy` makes a private copy of the input data.
(2) It uses `unsigned` counters in `flac_read_loop` and elsewhere, in place of `sf_count_t`.
The first change is …

Read more than 2^24 samples from FLAC file with non-power-of-two channels

---

tests/utils.tpl

Using exact comparison (e.g. `a == b`) when comparing expected with computed test data fails the test-suite on many architectures (including, but not limited to, `armhf` and `arm64`).
Instead, use epsilon(for now, `FLT_EPSILON` and `DBL_EPSILON`) to compare floating point numbers for equality.
Closes: https://github.com/libsndfile/libsndfile/issues/866

tests: Use fuzzy comparison in test-suite

---

include/sndfile.h

INT64_MAX instead of 0x7FFFFFFFFFFFFFFFLL avoids type discrepancy between int64_t and LL (long long) suffix when int64_t is not long long.

Define SF_COUNT_MAX as INT64_MAX.

---

src/mpeg_decode.c

Resolve #880 
Most every read api I've ever worked with return no error and positive byte counts, or zero bytes and an end or error condition. When the end of stream is reached, the last read will contain the last bytes, and the next call to read returns an error indicating that end has been reached.
But not mpg123, no, when reaching the last bytes, it returns the last bytes AND sets the error condition to done.
Assumptions make and ass of you an mumptions.

mpeg_decode: Fix bug where final bytes from mpg123_read() where ignored.

---

src/common.c
src/wavlike.c
tests/cpp_test.cc
tests/error_test.c

This triggered other minor fixes and cleanup. See the individual commits.

Let wav parsing recover from invalid LIST chunks, fixing #374

---

src/ogg.c

ogg: Check for NULL returns from ogg_sync_buffer (issue 863)

---

src/wavlike.c

Compile upgrades have found an existing set-but-unused variable in `wavlike_read_cart_chunk()`
Rather than remove the unread `bytes` variable (which possibly points to another bug, that read's don't appear to be bounded), use the bytes tally for a debug message about padding bytes.

wavlike: Find a use for unused bytes total

---

src/sndfile.c

The minimal possible MPEG file contains no headers or identification other than the brief sync header. This header is only 3 bytes, and is quite prone to false-positives. Particularly raw PCM can look like a sync header.
As such, move detection of 'naked' MPEG files in `guess_file_type()` to the very last test. Give more weight to a sync header if it follows an ID3 tag.
In issue #830, differences in libc random number functions mean that SD2 files generated by the test suite looked like mp3 files. SD2 files are raw data with the header stored in a resource fork. This PR move the test for 'naked' MPEG to after even checking for resource forks.
It may be preferable to remove the check for naked MPEG streams altogether, as if `guess_file_type()` can't return a match, …

Identify 'naked' MPEG streams last, even after resource forks

---

README
docs/index.md
vcpkg.json

The 1.2.0 release is not mentioned in the history of releases,
and 1.1.0 seems to have been left in a few places.
Why do we have both README and README.md?

version 1.2.0, not 1.1.0

---

CMakeLists.txt

This PR adds `Ogg::ogg` to the linked libraries since it is explicitly used in `src/ogg*.c` source files.
Previous to this PR, `Ogg::ogg` was provided transitively by Vorbis and FLAC, and as such not added to the `INTERFACE_LINK_LIBRARIES` of the exported target in static builds.
This problem can be reproduced the following way
- Build a static version of libsndfile with Xiph codecs
- Use a shared version of libvorbis and libFLAC
- Have a custom Find modules for Vorbis and FLAC that rely on pkg-config, or that do not search for transitive dependencies and relies on the user manually passing link flags when needed (e.g. [SDL2_mixer](https://github.com/libsdl-org/SDL_mixer/blob/SDL2/cmake/FindFLAC.cmake)).
Since both Vorbis and FLAC are shared, they have no link-time dependency, but sndfile …

CMake: Explicitly link against Ogg::ogg.

---

src/ogg.c

I compared the relative part of `ogg.c` with Xiph.org's opusfile-0.12/src/opusfile.c, and found there is a little difference between them. changing it makes #888 succeed.

fix #888, change diffrence of 'ret', 'offset' form Xiph.org's Opusfile: opusfile-0.12/src/opusfile.c

---

src/config.h.cmake
src/sfconfig.h

`HAVE_SSIZE_T` isn't defined when building with autotools, which results in `ssize_t` being defined and interfering with system headers when the real `ssize_t` is defined. Since autotools provides its own replacement, the relevant code has been moved to `config.h.cmake`.

Avoid redefining ssize_t when building with autotools

---

include/sndfile.hh

Adding move constructor and move assignment for `SndfileHandle` if the C++11 std or newer is supported.

Add move semantics for SndfileHandle if C++11 or newer

---

src/aiff.c
src/common.c

Two fixes related to the AIFF container.
Chunks inside of an AIFF file can come in any order. There are two places chunks which can specify channel count, the containing FORM chunk and the COMM chunk. The PEAK chunk doesn't specify a size, and is proportional to the known channel count. If the COMM chunk occurs after the PEAK chunk, and has a different channel count, the PEAK chunk should be discarded. Firstly because there is no reasonable behaviour on how to adapt the peak info, and secondly because the memory allocation for the peak info is no longer the correct size.
AIFF files can have an arbitrary gap between the end of the header data and the start of the audio data. (This is referenced by the AIFF spec as to aid accelerated filesystem block aligned writes.) These extra pad bytes, …

AIFF fixes

---

src/mpeg_decode.c

I encountered some funky MP3 files that are not using the ID3 container, and cannot be successfully read by sndfile. The library correctly identifies them as mpeg files based on the frame header, but it thinks they have no data because mpg123_length returns 0. According to the [mpg123 docs](https://www.mpg123.de/api/group__mpg123__status.shtml#ga7a97295f5dd82795489d9ed8ee544805), length relies on either an info header at the start of the file or a previous call to mpg123_scan.
Not sure if this is the most optimal solution, but it works. Let me know if my commit message is inaccurate, I'm not an audio programmer :)

mpeg: fix reading of mpeg files that lack an INFO header

---

docs/api.md
docs/bugs.md
docs/command.md
docs/development.md
docs/index.md
docs/linux_games_programming.txt
docs/lists.md

Found via `codespell -q 3 -S ./NEWS.OLD -L caf,chek,dout,levl,merchantibility,nd,sav,writen`

docs: fix various typos

---

src/common.h

Libsndfile currently directly includes `immintrin.h`, which does not work when compiling for ARM64EC with Visual Studio:
```
MSBuild version 17.7.0+5785ed5c2 for .NET Framework
1>Checking Build System
Building Custom Rule C:/.conan/456ac1/1/src/CMakeLists.txt
common.c
file_io.c
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.37.32820\include\immintrin.h(19,1): fatal  error C1189: #error:  this header should only be included through <intrin.h> (compiling source file C:\.conan\456ac1\1\src\src\common.c) [C:\.conan\456ac1\1\build\sndfile.vcxproj]
```

MSVC: Fix building with SSE and ARM64EC

---

src/wav.c

Libsndfile uses `int64_t` to represent datalength and filelength internally, but the wave/riff header is limited to `uint32`.  Ideally the user should stop writing to the file before reaching this max, but since the library allows writing the PCM data beyond this, it would in my opinion be better to clamp the header values instead of the wrap around we get today.
This is a minimal patch suggestion for wav, but might want to create a shared solution in `psf_binheader_writef` instead (or just disallow writing beyond the max, depending on preference)

Clamp wav header filelength and datalength

---

CHANGELOG.md
Makefile.am
configure.ac

* `autogen` is only required for bootstrapping the tests and not from release tarballs. Calling `touch` from configure scripts is brittle and doesn't work when `$srcdir` != `$builddir`.
Bug: https://bugs.gentoo.org/869815

Disable autogen make rules if autogen cannot be found

---

src/ALAC/ag_dec.c
src/ALAC/ag_enc.c
src/ALAC/alac_decoder.c
src/ALAC/alac_encoder.c
src/ALAC/matrix_dec.c
src/ALAC/matrix_enc.c

Get rid of compile warnings when compiled 32-bit on illumos.
See also: https://github.com/libsndfile/libsndfile/issues/966#issuecomment-1727389036

ALAC: Include config.h to avoid warnings

---

Makefile.am
ossfuzz/.gitignore
ossfuzz/sndfile_fuzz_header.h
src/aiff.c
src/au.c
src/avr.c
src/common.c
src/common.h
src/ima_adpcm.c
src/ircam.c
src/mat4.c
src/mat5.c
src/nms_adpcm.c
src/pcm.c
src/rf64.c
src/sds.c

Issues #789 and #833 alert that the clang fuzzer reports several numeric overflow possibilities throughout the codebase, which can lead to undefined behaviors. MITRE opened [CVE-2022-33065](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-33065) against these issues, and has issued them a high severity. This PR attempts to fix all the outstanding numeric overflows, as detected by the ossfuzzer tool, and the reproducing case from #789.
```
src/au.c:324:54: runtime error: signed integer overflow: 1684960000 + 779316836 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/au.c:324:54 in 
src/au.c:326:29: runtime error: signed integer overflow: 1684960000 + 779316836 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: …
```

Fix various numeric overflow vulns throughout code (CVE-2022-33065)

---

.github/workflows/action.yml

Update CI use of actions/checkout to version 4, addressing Github deprecation of actions that use older versions of nodejs.
Addresses #1024

ci: update Github action/checkout to v4

---

include/sndfile.hh

Might as well provide `operator !=` for a complete set of comparison operators

sndfile.hh: add `operator !=`

---

CMakeLists.txt
cmake/SndFileChecks.cmake
configure.ac
man/sndfile-play.1
programs/sndfile-play.c

Move the Sndio backend away from being OpenBSD specific and
make use of the pkg-config support.
Sndio is also used on FreeBSD and Linux.

Improvements for the Sndio backend support

---

configure.ac

Revert part of 3ab2093f32325fa5eeeb099d53064639c0e9a861 to fix
the handling of HAVE_SNDIO_H.

configure.ac: Fix HAVE_SNDIO_H handling

---

src/ALAC/alac_decoder.c
src/ALAC/alac_encoder.c

Include <stdbool.h> instead of redefining `bool`, `true` and `false` keywords

---

CMakeLists.txt
cmake/SndFileChecks.cmake

This allows building libsndfile using cmake 4.0. See issue #1076
Changes cmake_minimum_required minimum to 3.5, since  cmake 4.0 will not accept earlier versions
Changes cmake_minimum_required maximum to 4.0
Changes use of obsoleted package PythonInterp to Python which is current and is backwards compatible with older versions of cmake
Tested by building libsndfile via homebrew on macOS 13.7.5

Update build for using cmake 4, fixing issue #1076
